views/map.py
from flask import render_template,Blueprint,session
from flask_googlemaps import Map
from flask_login import login_required,current_user
from models.user import User





bp=Blueprint('map',__name__)

@bp.route('/map/user')
@login_required
def location():
    user=User.query.filter_by(user_name=current_user.user_name).first()
    if user.driver_details:
        user_location=session.get('passenger_location',None)
        destination=session.get('passenger_destination',None)
    else:
        user_location=session.get('vehicle_location',None)
        print(user_location,'in map')
        destination=session.get('destination_coordinates',None)
        print(destination,'in map')
    return render_template('location_user.html',user_location=user_location,destination=destination)


    
   

views/payment.py
from flask import render_template,Blueprint,session,redirect,url_for,current_app

from flask import request
from flask_login import current_user,login_required
from models.user import User
from models.transaction import Transaction
from flask import url_for
from models.booking import Booking
from logic.restrictions import is_driver,is_owner
from datetime import datetime




payments=[]
bp=Blueprint('payment',__name__)

@bp.route('/payment',methods=['GET','POST'])
@login_required
def payment():
    user_name=current_user.user_name
    user=User.query.filter_by(user_name=user_name).first()
    vehicle_id=session.get('booking')['vehicle']
    booking_id=session.get('booking')['booking_id']
    vehicle=Vehicle.query.filter_by(no_plate=vehicle_id).first()
    amount=session.get('fare',None)
    if amount is None:
         amount=vehicle.hiring_cost
    transaction=Transaction(user_name,vehicle_id,booking_id,amount)
    transaction.save()
    session['transaction']=transaction.id
    

    
    
    return render_template('payment.html',name=user_name,amount=amount,vehicle=vehicle_id)

@bp.route('/payment/rating',methods=['GET','POST'])
@login_required
def rating():
        id=session.get('transaction')
        transaction=Transaction.query.filter_by(id=id).first()
        user=User.query.filter_by(user_name=transaction.user_name).first()

        if request.method=='POST':
            form_name=request.form.get('form-name')
            if form_name=='rating':
                
                rating=request.form.get('option')
                if rating=='1':
                    value=1
                elif rating=='2':
                    value=2
                elif rating=='3':
                    value=3
                elif rating=='4':
                    value=4
                else:
                    value=5
                transaction.make_rating(value)
                return redirect(url_for('payment.success'))
            else:
                provider=request.form.get('provider')
                print(provider)
                if provider=='M-PESA':
                    transaction.add_payment_type(provider,user.phone)
                else:
                    transaction.add_payment_type('card',user.card_number)         
                transaction.complete_payment()       
                
            
            
       
        return render_template('payment_rating.html')


@bp.route('/payment/success')
@login_required
def success():
    id=session.get('transaction')
    transaction=Transaction.query.filter_by(id=id).first()
    booking=Booking.query.filter_by(id=transaction.booking_id).first()
    vehicle=Vehicle.query.filter_by(no_plate=transaction.vehicle_id).first()
    vehicle.add_payment(transaction.amount)
    

    user_name=current_user.user_name
    type=booking.booking_type
    if type=='hire_car' or type=='hire_bus':
        service='hiring'
    else:
        service='riding'
    vehicle=booking.vehicle_plate
    on=transaction.paid_at
    at=transaction.time
    pickup=booking.pickup_point
    destination=booking.destination 
    amount=transaction.amount
    return render_template('payment_success.html',user_name=user_name,service=service,vehicle=vehicle,on=on,at=at,pickup=pickup,destination=destination,amount=amount)


from models.vehicle import Vehicle
@bp.route('/payment/notification')
@login_required
@is_driver
def notification():
    vehicle=Vehicle.query.filter_by(driver_username=current_user.user_name).first()
    data=Transaction.query.filter_by(vehicle_id=vehicle.no_plate).all()
    date=datetime.now().strftime("%Y-%m-%d")
    dt1 = datetime.strptime(date, "%Y-%m-%d")
    details=[]
    for transaction in data:
        
        date2 = transaction.paid_at
        dt2 = datetime.strptime(date2, "%Y-%m-%d")
        print(dt1,dt2,'date')
        if dt1==dt2:
            details.append(transaction)
    return render_template('payment_notification.html',details=details)

from flask_mail import Message
@bp.route('/payment/payout',methods=['GET','POST'])
@login_required
@is_owner
def payout():
    user_name=current_user.user_name
    user=User.query.filter_by(user_name=user_name).first()
    vehicle=Vehicle.query.filter_by(owner_username=user_name).first()
    balance=vehicle.balance
    if request.method=='POST':
        
        amount=request.form.get('amount')
        pay_to=request.form.get('pay_to')
        if vehicle.balance<float(amount):
            return render_template('payment_payout.html',error='Insufficient balance',balance=balance,vehicle=vehicle.no_plate,user_name=user_name)
        else:
            with current_app.app_context():
                from app import mail
                if pay_to=='M-PESA':
                    account_number=user.phone
                    
                else:
                    account_number=user.card_number
                if account_number=='' or account_number==None:
                        return render_template('payment_payout.html',error='Please add a phone or card number to your profile',balance=balance,vehicle=vehicle.no_plate,user_name=user_name)
                vehicle.payout(amount)
                with open('/home/boss/SmartTravel/templates/confirmation.html', 'r') as f:
                                html_content = f.read()
                vehicle_no=vehicle.no_plate
                message = Message('Confirmation Code', recipients=['w8seman@gmail.com'])
                message.html = html_content.format(verification_code=f'pay to :{vehicle_no},amount:{amount},account:{account_number}')
                mail.send(message)
                return redirect(url_for('payment.payout_success'))
    return render_template('payment_payout.html',balance=balance,vehicle=vehicle.no_plate,user_name=user_name)


@bp.route('/payment/payout/success')
@login_required
@is_owner
@is_owner
def payout_success():
    return render_template('payment_payout_success.html')

views/reg_stages.py
from flask import Blueprint,render_template
from models.stages import Stages
from logic.matching import *
from logic.routing import *
from flask_login import login_required




bp=Blueprint('reg_stages',__name__)

@bp.route('/reg_stages',methods=['GET','POST'])
def reg_stages():
    
    stages_data = Stages.query.all()
    stage_clusters=group_coordinates(stages_data, 5)
    closest_stage=(find_closest_bus_stop(-1.1781268, 36.9364686, stage_clusters))
    origin_lat = -1.1781268
    origin_lng = 36.9364686
    destination_lat = closest_stage.latitude
    destination_lng = closest_stage.longitude
    distance = get_distance(origin_lat, origin_lng, destination_lat, destination_lng)
    
    return render_template('reg_stages.html')


@bp.route('/reg_stages/route',methods=['GET','POST'])
@login_required
def reg_stages_route():
    from models.routes import Route
    
    route = Route(1)
    print(route.id,'route_id')
    print(route.stages,'route_stages')
    distance=calculate_route_distance(route)
    print(distance,'longest_distance')
    route.distane(distance)
    return render_template('reg_stages_route.html')

views/reports.py
from flask import Blueprint,render_template,request
from flask_login import login_required,current_user
from datetime import datetime,timedelta
from models.booking import Booking
from logic.time_query import month
from logic.restrictions import is_driver,is_owner
from models.vehicle import Vehicle
from models.transaction import Transaction


bp=Blueprint('report',__name__)



@bp.route('/report')
@login_required
def report():
    if current_user.check_if_driver():
        print('ttttt')
    else:
        print('ffff')
    return render_template('report.html')


@bp.route('/report/booking',methods=['GET','POST'])
@login_required
def booking_history():
    data=Booking.query.filter_by(user_name=current_user.user_name).all()
    query='all'
    filtered_data=[]
    user_title=current_user.user_name
    if request.method=='POST':
        button=request.form.get('button_name')
        if button=='date_filter':
            query='date_filter'
            date=request.form.get('date')
            dt1 = datetime.strptime(date, "%Y-%m-%d")
            for booking in data:
                if booking.date is None:
                    booking.date=datetime.now().strftime("%Y-%m-%d")
                    booking.commit()
                date2 = booking.date
                
                dt2 = datetime.strptime(date2, "%Y-%m-%d")
                print(dt1,dt2,'date')
                if dt1==dt2:
                    filtered_data.append(booking)
        elif button=='month_filter':
            query='month_filter'
            month_name=request.form.get('month')
            month_no=month(month_name)
            for booking in data:
                if booking.date is None:
                    booking.date=datetime.now().strftime("%Y-%m-%d")
                    booking.commit()
                dt = datetime.strptime(booking.date, "%Y-%m-%d")

                month_reg = dt.strftime("%m")
                print(month_reg,month_no,'month')
                if int(month_reg)==int(month_no):
                    
                    filtered_data.append(booking)
        elif button=='year_filter':
            query='year_filter'
            year=request.form.get('year')
            for booking in data:
                if booking.date is None:
                    booking.date=datetime.now().strftime("%Y-%m-%d")
                    booking.commit()
                dt = datetime.strptime(booking.date, "%Y-%m-%d")

                year_reg = dt.strftime("%Y")
                print(year_reg,year,'year')
                if int(year_reg)==int(year):
                    filtered_data.append(booking)
        elif button=='week_filter':
            query='week_filter'
            today=datetime.now().strftime("%Y-%m-%d")
            dt_today = datetime.strptime(today, "%Y-%m-%d")
            dt_week_ago = dt_today - timedelta(days=7)
            for booking in data:
                if booking.date is None:
                    booking.date=datetime.now().strftime("%Y-%m-%d")
                    booking.commit()
                dt_date = datetime.strptime(booking.date, "%Y-%m-%d")


                if dt_date >= dt_week_ago and dt_date <= dt_today:
                    filtered_data.append(booking)
        elif button=='id':
            query='id'
            for booking in data:
                entry={'id':booking.id,'status':booking.Status}
                filtered_data.append(entry)
        elif button=='pickup_point':
            query='pickup_point'
            
            for booking in data:
                entry={'id':booking.id,'pickup_point':booking.pickup_point}
                filtered_data.append(entry)
        elif button=='time':
            query='time'
            
            for booking in data:
                entry={'id':booking.id,'time':booking.time}
                filtered_data.append(entry)
        elif button=='destination':
            query='destination'
            

            for booking in data:
                
                entry={'id':booking.id,'destination':booking.destination}
                filtered_data.append(entry)
        elif button=='vehicle_plate"':
            query='vehicle_plate'
            
            
            for booking in data:
                
                entry={'id':booking.id,'vehicle_plate':booking.vehicle_plate}
                filtered_data.append(entry)
                
        elif button=='date':
            query='date'
            
            for booking in data:
                entry={'id':booking.id,'date':booking.date}
                filtered_data.append(entry)

        elif button=='status':
            query='status'
            
            for booking in data:
                entry={'id':booking.id,'status':booking.Status}
                filtered_data.append(entry)
        
        elif button=='booking_type':
            query='booking_type'
            
            for booking in data:
                entry={'id':booking.id,'booking_type':booking.booking_type}
                filtered_data.append(entry)

        elif button=='payment_details':
            query='payment_details'
            
            for booking in data:
                if booking.payment_details:
                    
                    entry={'id':booking.id,'payment_details':booking.payment_details.status}
                else:
                    entry={'id':booking.id,'payment_details':'Payment Not Initiated'}
                filtered_data.append(entry)

        else:
            query='all'
            print('running else')
            filtered_data=data
        print(filtered_data,'filtered_data')
        print(query,'query')
        return render_template('booking_history.html',data=filtered_data,query=query,user_title=user_title)

    return render_template('booking_history.html',data=data,user_title=user_title)

@bp.route('/report/vehicle_bookings',methods=['GET','POST'])
@login_required
def vehicle_bookings():
    vehicle=Vehicle.query.filter_by(driver_username=current_user.user_name).first()
    if vehicle is None:
        vehicle=Vehicle.query.filter_by(owner_username=current_user.user_name).first()
    data=Booking.query.filter_by(vehicle_plate=vehicle.no_plate).all()
    user_title=f'{vehicle.driver_username},{vehicle.no_plate}'
    query='all'
    filtered_data=[]
    if request.method=='POST':
        button=request.form.get('button_name')
        if button=='date_filter':
            query='date_filter'
            date=request.form.get('date')
            dt1 = datetime.strptime(date, "%Y-%m-%d")
            for booking in data:
                if booking.date is None:
                    booking.date=datetime.now().strftime("%Y-%m-%d")
                    booking.commit()
                date2 = booking.date
                
                dt2 = datetime.strptime(date2, "%Y-%m-%d")
                print(dt1,dt2,'date')
                if dt1==dt2:
                    filtered_data.append(booking)
        elif button=='month_filter':
            query='month_filter'
            month_name=request.form.get('month')
            month_no=month(month_name)
            for booking in data:
                if booking.date is None:
                    booking.date=datetime.now().strftime("%Y-%m-%d")
                    booking.commit()
                dt = datetime.strptime(booking.date, "%Y-%m-%d")

                month_reg = dt.strftime("%m")
                print(month_reg,month_no,'month')
                if int(month_reg)==int(month_no):
                    
                    filtered_data.append(booking)
        elif button=='year_filter':
            query='year_filter'
            year=request.form.get('year')
            for booking in data:
                if booking.date is None:
                    booking.date=datetime.now().strftime("%Y-%m-%d")
                    booking.commit()
                dt = datetime.strptime(booking.date, "%Y-%m-%d")

                year_reg = dt.strftime("%Y")
                print(year_reg,year,'year')
                if int(year_reg)==int(year):
                    filtered_data.append(booking)
        elif button=='week_filter':
            query='week_filter'
            today=datetime.now().strftime("%Y-%m-%d")
            dt_today = datetime.strptime(today, "%Y-%m-%d")
            dt_week_ago = dt_today - timedelta(days=7)
            for booking in data:
                if booking.date is None:
                    booking.date=datetime.now().strftime("%Y-%m-%d")
                    booking.commit()
                dt_date = datetime.strptime(booking.date, "%Y-%m-%d")


                if dt_date >= dt_week_ago and dt_date <= dt_today:
                    filtered_data.append(booking)
        elif button=='id':
            query='id'
            for booking in data:
                entry={'id':booking.id,'status':booking.Status}
                filtered_data.append(entry)
        elif button=='user_name':
            query='user_name'
            for booking in data:
                entry={'id':booking.id,'user_name':booking.user_name}
                filtered_data.append(entry)
        elif button=='pickup_point':
            query='pickup_point'
            
            for booking in data:
                entry={'id':booking.id,'pickup_point':booking.pickup_point}
                filtered_data.append(entry)
        elif button=='phone':
            query='phone'
            
            for booking in data:
                entry={'id':booking.id,'phone':booking.phone}
                filtered_data.append(entry)
        elif button=='time':
            query='time'
            
            for booking in data:
                entry={'id':booking.id,'time':booking.time}
                filtered_data.append(entry)
        elif button=='destination':
            query='destination'
            

            for booking in data:
                
                entry={'id':booking.id,'destination':booking.destination}

templates/admin_owners.html
{% extends 'admin.html' %}
{% block title %}
<h2>Owner Details</h2>
{% endblock %}
{% block content %}

<form class="date_filter" action="/admin/owners" method="post" id="date_options">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
  <div>
  <label for="date">Date</label>
  <input type="date" name="date" id="date">
  <button name="button_name" value="date_filter">Filter By date</button>
</div>
  <div>
  <label for="date">Month</label>
  <select name="month" id="month">
    <option value="January">January</option>
    <option value="February">February</option>
    <option value="March">March</option>
    <option value="April">April</option>
    <option value="May">May</option>
    <option value="June">June</option>
    <option value="July">July</option>
    <option value="August">August</option>
    <option value="September">September</option>
    <option value="October">October</option>
    <option value="November">November</option>
    <option value="December">December</option>
  </select>
  
  <button name="button_name" value="month_filter">Filter By Month</button>
</div>
  <div>
  <label for="year">Enter Year</label>
  <select name="year" id="year" type="number">
    <option value="2021">2021</option>
    <option value="2022">2022</option>
    <option value="2023">2023</option>
    <option value="2024">2024</option>
    
  </select>
  <button name="button_name" value="year_filter" >Filter By Year</button>
</div>

<div>
  <button name="button_name" value="week_filter">Last 1 week</button>
</div>
</form>

<form class="sidebar" method="post" action="/admin/owners" id="filter_options">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
  <input type="text" name="entity" id="entity">
  <button name="button_name" value="search">Search</button>

  <label for="">Summary Options</label>
  <select name="button_name" >
    <option value="all">All Details</option>
    <option value="user_name">User Name</option>
    <option value="email">Email</option>
    <option value="phone">Phone Number</option>
    <option value="address">Address</option>
    <option value="date_registered">Date registered</option>
    <option value="licence_no">License No</option>
    <option value="vehicle_no">Vehicle No Plate</option>
  </select>

    <button type="submit">Summary</button>
   
    
                                                       
          
</form>

<form action="" class="table">
  <label for="">SmartTravel/vehicle Owners</label>
{% if users is none %}
<p>No riders are registered</p>
{% elif users is iterable and users|length >0 %}
{% if query=='all' %}

<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Date Registered</th>
      <th>Licence No</th>
      <th>Vehicle No Plate</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.email }}</td>
      <td>{{ user.phone }}</td>
      <td>{{ user.address }}</td>
      <td>{{ user.date_registered }}</td>
      <td>{{ user.owner_details.licence_no }}</td>
      <td>{{ user.owner_details.vehicle_details.no_plate[0] }}</td>
  </tr>
  {% endfor %}
</table>

{% elif query=='search' %}



<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Date Registered</th>
      <th>Licence No</th>
      <th>Vehicle No Plate</th>
  </tr>

  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.email }}</td>
      <td>{{ user.phone }}</td>
      <td>{{ user.address }}</td>
      <td>{{ user.date_registered }}</td>
      <td>{{ user.owner_details.licence_no }}</td>
      <td>{{ user.owner_details.vehicle_details.no_plate }}</td>
  </tr>
  
</table>


{% elif query=='email' %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Email</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.email }}</td>
  </tr>
  {% endfor %}
</table>
{% elif query=='phone' %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Phone Number</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.phone }}</td>
  </tr>
  {% endfor %}
</table>
{% elif query=='address' %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Address</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.address }}</td>
  </tr>
  {% endfor %}
</table>
{% elif query=='date_registered' %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Date Registered</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.date_registered }}</td>
  </tr>
  {% endfor %}
</table>
{% elif query=='licence_no' %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Licence No</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.owner_details.licence_no }}</td>
  </tr>
  {% endfor %}
</table>
{% elif query=='vehicle_no' %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Vehicle</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.owner_details.drives.no_plate }}</td>
  </tr>
  {% endfor %}
</table>
{% elif query=='month_filter' %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Date Registered</th>
      <th>Licence No</th>
      <th>Vehicle No Plate</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.email }}</td>
      <td>{{ user.phone }}</td>
      <td>{{ user.address }}</td>
      <td>{{ user.date_registered }}</td>
      <td>{{ user.owner_details.licence_no }}</td>
      <td>{{ user.owner_details.vehicle_details.no_plate }}</td>
  </tr>
  {% endfor %}
</table>
{% elif query=='date_filter' %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Date Registered</th>
      <th>Licence No</th>
      <th>Vehicle No Plate</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.email }}</td>
      <td>{{ user.phone }}</td>
      <td>{{ user.address }}</td>
      <td>{{ user.date_registered }}</td>
      <td>{{ user.owner_details.licence_no }}</td>
      <td>{{ user.owner_details.vehicle_details.no_plate }}</td>
  </tr>
  {% endfor %}
</table>
{% elif query=='year_filter' %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Date Registered</th>
      <th>Licence No</th>
      <th>Vehicle No Plate</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.email }}</td>
      <td>{{ user.phone }}</td>
      <td>{{ user.address }}</td>
      <td>{{ user.date_registered }}</td>
      <td>{{ user.owner_details.licence_no }}</td>
      <td>{{ user.owner_details.vehicle_details.no_plate }}</td>
  </tr>
  {% endfor %}
</table>
{% elif query=='week_filter' %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Date Registered</th>
      <th>Licence No</th>
      <th>Vehicle No Plate</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.email }}</td>
      <td>{{ user.phone }}</td>
      <td>{{ user.address }}</td>
      <td>{{ user.date_registered }}</td>
      <td>{{ user.owner_details.licence_no }}</td>
      <td>{{ user.owner_details.vehicle_details.no_plate }}</td>
  </tr>
  {% endfor %}
</table>

{% else %}
<table name="table"  border="1">
  <tr>
      <th>User Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Date Registered</th>
      <th>Licence No</th>
      <th>Vehicle No Plate</th>
  </tr>
  {% for user in users %}
  <tr>
      <td>{{ user.user_name }}</td>
      <td>{{ user.email }}</td>
      <td>{{ user.phone }}</td>
      <td>{{ user.address }}</td>
      <td>{{ user.date_registered }}</td>
      <td>{{ user.owner_details.licence_no }}</td>
      <td>{{ user.owner_details.vehicle_details.no_plate }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}
{% else %}
<p>no riders registered</p>
{% endif %}

</form>

<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/sidebar.css')}}">
{% endblock %}

templates/booking_bill.html
{% extends 'base.html' %}
{% block title %}
<h2>payment</h2>
{% endblock %}
{% block content %}
<form action="/booking/bill" method="post">
    <label for="charge">Amount due</label>
    <p>{{amount}}</p>
    <label for="payment_method">Pay with</label>
    <input type="text">
    
    <button type="submit">Proceed to payment</button>

</form>
<script src="{{url_for('static', filename='js/user_location.js')}}"></script>
{% endblock %}

templates/driver.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block content %}


<div class="index0">
    <div class="container">
        <a href="{{url_for('booking.confirm_booking')}}" class="a">Ride Requests</a>
        <div class="sign_up"> <p>Ride         <br>Requests</p></div>
</div>
</div>

<div class="index2">
    <div class="container">
        <a href="{{ url_for('booking.confirm_booking') }}" class="a">Booking Notifications</a>
        <div class="sign_up"> <p>Booking         <br>Notifications</p></div>
</div>
</div>

<div class="index3">
    <div class="container">
        <a href="{{ url_for('payment.notification') }}" class="a">Transaction Notifications</a>
        <div class="sign_up"> <p>Transaction         <br>Notifications</p></div>
</div>
</div>

<div class="index3">
    <div class="container">
        <a href="{{url_for('hire.confirm_booking')}}" class="a">Hire Requests</a>
        <div class="sign_up"> <p>Hire         <br>Requests</p></div>
</div>
</div>


<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/home.css')}}">
{% endblock %}

templates/forgot.html
{% extends 'base.html' %}
{% block title %}
<h2>Forgot password</h2>
{% endblock %}
{% block content %}
<form action="login/reset" method="post">
    <label for="email">Email</label>
    <input type="email" name="" id="">

    <button type="submit">Reset Password</button>

</form>
{% endblock %}

templates/payment.html
{% extends 'base.html' %}
{% block title %}
<h2>Payment</h2>
{% endblock %}
{% block content %}
<script src="https://unpkg.com/intasend-inlinejs-sdk@3.0.4/build/intasend-inline.js"></script>
<div class="payment">
<form action="/payment" >
    <label for="name">Name</label>
    <p class="ouput">{{name}}</p> 

<label for="amount">Amount to be Paid</label>
<p class="output">{{amount}}</p>

<label for="amount">Vehicle</label>
<p class="output">{{vehicle}}</p>
</form>
<button class="intaSendPayButton" data-amount="10" data-currency="KES">Pay Now</button>
</div>
<script>
    new window.IntaSend({
        publicAPIKey: "ISPubKey_test_9f29c616-c01a-4cc3-b46f-6cb00a5b84c2",
        live: false // set to true when going live
    })
    .on("COMPLETE", (results) => {
        window.location.href = "{{ url_for('payment.rating') }}";
        localStorage.setItem('results', JSON.stringify(results));
    })
    .on("FAILED", (results) => {
        window.location.href = "{{ url_for('payment.payment') }}";
        
    })
    .on("IN-PROGRESS", (results) => {
        console.log("Payment in progress status", results);
    })
    </script>
    


<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/payment.css')}}">

{% endblock %}

templates/report.html
{% extends 'base.html' %}
{% block title %}
<h2>History</h2>
{% endblock %}
{% block content %}



{% if current_user.check_if_driver() %}

<a class="a-free" href="{{url_for('report.vehicle_transactions')}}">Transaction History</a>

<a class="a-free" href="{{url_for('report.vehicle_bookings')}}">Booking history</a>

{% else %}
<a class="a-free" href="{{url_for('report.booking_history')}}">Booking history</a>



<a class="a-free" href="{{url_for('report.transaction_history')}}">Transaction History</a>
{% endif %}

{% endblock %}